on: push
name: deploy
jobs:
  deploy:
    name: create and push image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: build and push to dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: prah/exp-logdepot
          tags: latest
